version: "3.0"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cve202135042
      - POSTGRES_USER=cve202135042
      - POSTGRES_PASSWORD=123456
  web:
    build: .
    command: /bin/sh -c "sleep 10 && python manage.py makemigrations vul_app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
